In [133]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from ipywidgets import interact
from ipywidgets import interact_manual

In [134]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
LZ = np.array([5, -1, 3, 9, 0, -5, 9, 7,-2])

In [3]:
ADOTB = matrix1 @ matrix2
ABYB = matrix1 * matrix2
print ( matrix1 @ matrix2 ) # 矩陣相乘
print ( matrix1 * matrix2 ) # 對應相乘:
print(LZ[(LZ>0)&(LZ<10)])   # 尋找陣列內大於0和10 

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[5 3 9 9 7]


In [97]:
Q1Sales = np.array(['Bill','Elisa','Gina','Joser','Jack','Phyia','David','Tom','Clair','Kevin'])
Q2Sales = np.array(['Kevin','Bill','Bill','Kevin','Jack','Clair','David','Tom','Clair','Kevin'])
Q3Sales = np.array(['Bill','Kevin','David','Joser','Clair','Kevin','David','Tom','Jack','Kevin'])
Q4Sales = np.array(['Joser','Kevin','Joser','Tom','Tom','Joser','David','Tom','Phyia','Kevin'])

ID_Def = 200
SalesID = [i for i in range(0+ID_Def,39+ID_Def)]  

Q1Sales_list=list(Q1Sales)
Q2Sales_list=list(Q2Sales)
Q3Sales_list=list(Q3Sales)
Q4Sales_list=list(Q4Sales)

Q1Sales_list.extend(Q2Sales_list)
Q1Sales_list.extend(Q3Sales_list)
Q1Sales_list.extend(Q4Sales_list)

TotalSales = np.array(Q1Sales_list)
#TotalSales = list(enumerate(np.array(Q1Sales_list)))
TotalSales = list(zip(SalesID,TotalSales))
# TotalSales[(TotalSales =='Clair')]

In [96]:
TotalSales

[(200, 'Bill'),
 (201, 'Elisa'),
 (202, 'Gina'),
 (203, 'Joser'),
 (204, 'Jack'),
 (205, 'Clair'),
 (206, 'David'),
 (207, 'Tom'),
 (208, 'Clair'),
 (209, 'Kevin'),
 (210, 'Danie'),
 (211, 'Ben'),
 (212, 'Shanne'),
 (213, 'Joseph'),
 (214, 'Joneson'),
 (215, 'Roger'),
 (216, 'Jenson'),
 (217, 'Winne'),
 (218, 'Jeff'),
 (219, 'Leo')]

In [137]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from ipywidgets import interact
from ipywidgets import interact_manual

# 自動幫團隊編號
Team1 = np.array(['Bill','Elisa','Gina','Joser','Jack'])
Team2 = np.array(['Clair','David','Tom','Clair','Kevin'])
Team3 = np.array(['Danie','Ben','Shanne','Joseph','Joneson'])
# 輸入團隊起始編號
Def_id =int( input('Input Team1 Default ID Number :'))
Team1_id = [i for i in range(0+Def_id,5+Def_id)]  
Def_id =int( input('Input Team2 Default ID Number :'))
Team2_id = [i for i in range(0+Def_id,5+Def_id)]  
Def_id =int( input('Input Team3 Default ID Number :'))
Team3_id = [i for i in range(0+Def_id,5+Def_id)]  
# 團隊編號+團隊名稱
Team1Member = dict(zip(Team1_id,Team1))
Team2Member = dict(zip(Team2_id,Team2))
Team3Member = dict(zip(Team3_id,Team3))
print(Team1Member)
print(Team2Member)
print(Team3Member)

Input Team1 Default ID Number :100
Input Team2 Default ID Number :200
Input Team3 Default ID Number :300
{100: 'Bill', 101: 'Elisa', 102: 'Gina', 103: 'Joser', 104: 'Jack'}
{200: 'Clair', 201: 'David', 202: 'Tom', 203: 'Clair', 204: 'Kevin'}
{300: 'Danie', 301: 'Ben', 302: 'Shanne', 303: 'Joseph', 304: 'Joneson'}
